version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}        # <-- keep your real root pwd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DB_PWD}             # <-- keep your real app pwd
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - internal

  app:
    image: nextcloud:29-apache
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - MYSQL_PASSWORD=${DB_PWD}             # must match above
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - APACHE_DISABLE_REWRITE_IP=1
    volumes:
      - ./data:/var/www/html
    networks:
      - internal
      - web
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.nextcloud.rule=Host(`cloud.mydomain.com`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"

      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
       # ðŸ‘‡ NEW: tell Traefik which Docker network/IP to use
      - "traefik.docker.network=web"
networks:
  internal:
    driver: bridge
  web:
    external: true
